--- #YAML:1.0
name:               POE-Component-Server-TacacsPlus
version:            1.11
abstract:           POE Tacacs+ server component
author:
    - Jozef Kutej <jkutej@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Clan:           0
    Log::Log4perl:        0
    Net::TacacsPlus::Client:  1.09
    Net::TacacsPlus::Constants:  1.09
    Net::TacacsPlus::Packet:  1.09
    POE:                  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
